services:
  postgres:
    image: postgres:16-alpine
    container_name: parcelar-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fi123456@
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parcelar-backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3006:3006"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:Fi123456%40@postgres:5432/restaurant?schema=public
      - FRONTEND_URL=http://localhost:3007
      - NEXT_PUBLIC_API_URL=http://localhost:3006
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads:/app/public/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parcelar-frontend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3006
      - PORT=3007
    depends_on:
      - backend

volumes:
  pgdata: 
  uploads:
